// DO NOT EDIT: this file is automatically derived from usage/stfinvany_description_usage.txt
#include "stfinvany_description_usage.h"
char stfinvany_description_usage[]=
{
  "How to control the procedure\n"
  "----------------------------\n"
  "A specific procedure is selected by passing a parameter string. This string\n"
  "may further contain parameters to control the way the procedure will be\n"
  "applied.\n"
  "\n"
  "The parameter string starts with an ID-sequence identifying the desired\n"
  "procedure. See the list available procedures for ID strings. In the parameter\n"
  "string the ID-sequence is terminated by a colon (:).\n"
  "\n"
  "After selecting the desired procedure, the interface function strips off the\n"
  "ID-sequence as well as the first colon from the parameter string. The\n"
  "remainder may consist of several control parameters being separated by colons\n"
  "(:). Each control parameter may just be a flag (switch to turn on an option)\n"
  "or may come along with a parameter value. The value is separated from the\n"
  "parameter by an equal sign (=).\n"
  "\n"
  "Where several values in an argument to a parameter must be separated (like in\n"
  "the 'irtap' option of the Fourier domain procedures) white space ( ), commas\n"
  "(,), and semicolons (;) are allowed as field delimiters, at your convenience.\n"
  "\n"
  "Examples:\n"
  "- To select Fourier domain least squares and shift the returned source\n"
  "  correction filter wavelet by 0.4s and switch on verbose mode, pass the\n"
  "  following parameter string:\n"
  "    fdlsq:tshift=0.4:verbose\n"
  "- To select the identity procedure and switch on debug level 4:\n"
  "    ident:DEBUG=4\n"
  "- To select Fourier domain least squares, apply offset dependent weights and\n"
  "  use a power of two to speed up the FFT:\n"
  "    fdlsq:pow2:exp=1.4\n"
};
