// DO NOT EDIT: this file is automatically derived from usage/stfinvfdleastsquares_description_usage.txt
#include "stfinvfdleastsquares_description_usage.h"
char stfinvfdleastsquares_description_usage[]=
{
  "Procedure: Least squares in the frequency domain\n"
  "------------------------------------------------\n"
  "This procedure calculates a least squares fit in the Fourier domain, which\n"
  "equals a waterlevel-deconvolution. A waterlevel as a fraction of the signal\n"
  "energy of the input synthetics is applied. If selected, offset dependent\n"
  "weights will be applied to the signals from different receivers.\n"
  "\n"
  "Options and parameters:\n"
  "  waterlevel=l  waterlevel to be applied for regularization.\n"
  "\n"
  "The procedure is implemented in the Fourier domain. Fourier coefficients for\n"
  "the correction filter are constructed such that the residual between Fourier\n"
  "coefficients of recorded signals and Fourier coefficients of synthetic signals\n"
  "after application of the correction filter are minimized in a least-squares\n"
  "sense. The least-squares solution is subject to a damping constraint. If the\n"
  "weighted power spectral density of the synthetics at a given frequency drops\n"
  "below the l-th fraction (waterlevel parameter) of the average (over all\n"
  "frequencies) power spectral density, the filter coefficients are damped\n"
  "(artificially made smaller) by the damping constraint (i.e. waterlevel as seen\n"
  "from the perspective of deconvolution). \n"
  "\n"
  "Start with l=0.01 as a reasonable initial value for the waterlevel. The best\n"
  "fitting waterlevel must be searched by trial and error and depends of signal\n"
  "noise and on how well the synthetics describe the actually observed wave\n"
  "propagtion.\n"
  "\n"
  "The theory behind the Fourier domain least squares procedure is outlined by\n"
  "Lisa Groos (2013, Appendix F, page 146). She also describes a way to find an\n"
  "approrpiate waterlevel by application of the L-curve criterion (Groos, 2013,\n"
  "Appendix G, page 148).\n"
  "\n"
  "Lisa Groos. 2013. 2D full waveform inversion of shallow seismic Rayleigh waves.\n"
  "  Dissertation, Karlsruhe Institute of Technology.\n"
  "  http://nbn-resolving.org/urn:nbn:de:swb:90-373206\n"
};
