// DO NOT EDIT: this file is automatically derived from usage/stfinvfourier_description_usage.txt
#include "stfinvfourier_description_usage.h"
char stfinvfourier_description_usage[]=
{
  "Options and parameters in common for procedures in the Fourier domain:\n"
  "  fpow2              use power of two for number of coefficients\n"
  "  fdiv=d             use integer multiple of d for number of coefficients\n"
  "  fpad=f             padding factor\n"
  "  tshift=d           delay source correction filter wavelet by d (in seconds)\n"
  "                     in order to expose acausal components\n"
  "  irtap=t1,t2,t3,t4  taper impulse response of correction filter\n"
  "\n"
  "These options define the number of samples N used for the FFT (Fast Fourier\n"
  "Transform). This number N should be larger than the number of samples M in the\n"
  "original input time series to avoid wrap-around. If fpow2 is set, N will be\n"
  "the next power of 2 larger than M*f. Else if fdiv is set, N will be the next\n"
  "integer multiple of d larger than M*f. If fdiv is not set explicitely, a\n"
  "default value for d (commonly 100) is used. If option fpad ist used, N will be\n"
  "f times larger than without padding. Without explicitely setting fpad, a\n"
  "default value for f is used (which commonly equals 1.5). When defining the\n"
  "number of samples N, first padding is considered (fpad), then the either\n"
  "selection of a power of two (pow2) or the divisor criterion (fdiv) is applied.\n"
  "The latter is only applied, if pow2 ist not selected.\n"
  "\n"
  "Input time series with M samples will be padded with (N-M) zeros to create the\n"
  "time series which actually will be transformed to the Fourier domain. Upon\n"
  "inverse FFT the additional (N-M) samples of the resulting time series will be\n"
  "discarded before returning the M remaining samples to the caller. Note, that\n"
  "this is a form of implicite taper. In particular the caller will not obtain\n"
  "exactly the filter response, which was used for convolution internally.\n"
  "\n"
  "The derived correction filter in some cases can contain acausal components.\n"
  "This means that the impulse response is non-zero for negative time values.\n"
  "Since by definition, the impulse response is output for the time interval of\n"
  "the input data, these acausal components can remain unnoticed. The option\n"
  "tshift can be used to shift the impulse response as obtained by inverse FFT in\n"
  "order to expose acausal components.\n"
  "\n"
  "A time domain taper can be applied to the impulse response of the correction\n"
  "filter by using option irtap. Four time values are given in units of seconds:\n"
  "t1, t2, t3, and t4. They must be in increasing order and (t4-t1) must be\n"
  "smaller than the total duration of the time series used to represent signals\n"
  "internally. Times value are allowed to be negative. Time series are understood\n"
  "to be periodic (due to discrete Fourier transformation). Prior to application\n"
  "of the correction filter to the time series passed to the algorithm, the\n"
  "correction filter is transformed to the time domain, tapered, and then\n"
  "transformed to the Fourier domain again. The values of the taper are:\n"
  "  0                              if       t <  t1\n"
  "  0.5-0.5*cos(pi*(t-t1)/(t2-t1)) if t1 <= t <= t2\n"
  "  1                              if t2 <  t <  t3\n"
  "  0.5+0.5*cos(pi*(t-t3)/(t3-t4)) if t3 <= t <= t4\n"
  "  0                              if       t >  t4\n"
  "\n"
  "Time values are given in the same unit in which the sampling interval is given\n"
  "in the input time series. I.e. if sampling interval is specified as a fraction\n"
  "of seconds (which is standard) then all time values passed as parameters are\n"
  "also given as fractions or multiples of seconds.\n"
};
